Work
cristichirtos/RoR-internship-assignment-1 pull request #1
Opened 2021-04-11 13:27 UTC by cristichirtos

2021-04-12 07:13 UTC, AdrianFlorian requested changes
Nice job Cristi 💪👏 , just a few things in general:
- avoid duplicated code by using multiple methods
- methods that do too many things should be broken down into smaller methods with a descriptive name
- How to write better commit messages: https://chris.beams.io/posts/git-commit/

2021-04-12 07:13 UTC, AdrianFlorian commented on index.html
> +            <p class = "logotext"> Eureka<br>Caffe</p>
Watch out on the spacing :-) `<p class = "logotext"> Eureka <br> Caffe </p>` even if the compiler doesn't care about it, it has to be pretty on the inside as well :-)

2021-04-12 07:13 UTC, AdrianFlorian commented on script.js
> +    dishName.className = "dishName";
I see a lot of duplicated code here, is it possible to group this code into multiple methods and simplify the logic?
See my message in #ror-internship

2021-04-12 07:13 UTC, AdrianFlorian commented on script.js
> +    const elementList = JSON.parse(localStorage.getItem('elements') || "[]");
This part (line 131 -> 137) could go in a new method, what do you think?

2021-04-12 07:14 UTC, AdrianFlorian commented
@cristichirtos also, let's work on a better Pull Request name - the PR name should contain a quick overview of the changes that your code contain :-)

2021-04-12 07:21 UTC, cristichirtos commented on script.js
> +    const elementList = JSON.parse(localStorage.getItem('elements') || "[]");
I think so too, I'm working on it. Thanks!

2021-04-12 07:35 UTC, cristichirtos commented on index.html
> +            <p class = "logotext"> Eureka<br>Caffe</p>
Missed that one, thank you!

2021-04-12 07:35 UTC, cristichirtos commented on script.js
> +    dishName.className = "dishName";
Working on a better solution right now.

2021-04-12 08:04 UTC, cristichirtos commented
I have implemented the request changes and updated the PR name and description. I'm here if you see more things that can be improved!

2021-04-12 08:56 UTC, chioreandan commented on index.html
> +                    <li>CONTACTS</li>
Indentation for your project should be 2 spaces instead of 4

2021-04-12 08:56 UTC, chioreandan commented on index.html
> +            <p class = "logotext"> Eureka<br>Caffe</p>
@cristichirtos In HTML you don't need to add a space `class` and `=`. 
`<p class="logotext"> Eureka <br> Caffe </p>`

2021-04-12 08:56 UTC, chioreandan commented on index.html
> +            <p class = "logotext"> Eureka<br>Caffe</p>
That way is easier to read

2021-04-12 09:00 UTC, chioreandan requested changes

2021-04-12 09:00 UTC, chioreandan commented on style.css
> +form {
Don't override styling of native components. The best approach is to create a wrapper class and add the styling there. If you need 2 form components with different styling in the same page you will have the same styling and you don't want that.

2021-04-12 09:00 UTC, chioreandan commented on script.js
> +}
add an empty line at the end of each file

2021-04-12 09:13 UTC, cristichirtos commented on index.html
> +            <p class = "logotext"> Eureka<br>Caffe</p>
I enjoy it with spaces more, but if it improves readability in HTML, I will modify them.

2021-04-12 13:06 UTC, cristichirtos commented
@AdrianFlorian @chioreandan I implemented the changes you have requested. Let me know what you think!

2021-04-12 13:19 UTC, AdrianFlorian requested changes
nice! Just one thing about the log and you're good to go from my end :-)

2021-04-12 13:19 UTC, AdrianFlorian commented on script.js
> +        console.log("loading from local storage");
Logs should only be used in development, please remove this one when pushing changes :-)

2021-04-12 13:19 UTC, AdrianFlorian commented on script.js
> +function createDishElement(element) {
nice 👍

2021-04-12 13:25 UTC, cristichirtos commented on script.js
> +        console.log("loading from local storage");
I forgot the logs, thanks for the heads up!

2021-04-12 13:25 UTC, cristichirtos commented on script.js
> +function createDishElement(element) {
Thank you!

2021-04-13 07:02 UTC, AdrianFlorian approved these changes
Nice 👏

2021-04-13 07:32 UTC, chioreandan requested changes
Looks good @cristichirtos,
Just a small request change and you are good to go.

2021-04-13 07:32 UTC, chioreandan commented on style.css
> +}
As a rule, it's not ok to override the native HTML components like header, nav, main, etc. 

> Dan Chiorean  12:19 PM
Inca o regula generala. Incercati sa nu puneti styling pe componente HTML native cum ar fi form, nav, img, etc  pentru ca e posibil sa aveti nevoie sa folositi aceasi componenta in locuri diferite dar cu styling diferit si atunci o sa va faca ovverride peste tot. Incercati sa folositi clase pentru a face styling-ul pe componenta respectiva

2021-04-13 07:47 UTC, cristichirtos commented on style.css
> +}
I added a class attribute for the header element, but not for the main element, as I only override an element inside of it, not main itself.

2021-04-13 17:49 UTC, chioreandan reviewed
1 small comment 💯

2021-04-13 17:49 UTC, chioreandan commented on index.html
> +  </head>
Try to add empty lines after this kind of sections

2021-04-14 06:38 UTC, cristichirtos commented on index.html
> +  </head>
I added spaces after all major elements in the HTML file. What do you think?

2021-04-15 06:19 UTC, chioreandan requested changes
Please apply the changes everywhere it is applicable

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    const price = createHTMLElement("p", "price");
add space after constants declaration

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    infoContainerDiv.appendChild(price);
Add empty line after method actions

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    return newHTMLElement;
same as above

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    const elementList = JSON.parse(localStorage.getItem('elements') || "[]");
add empty line after const declaration

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    const containerParent = document.getElementById("container");
add space after constants declaration

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    const image = createHTMLElement("img", "food-img");
add space after constants declaration

2021-04-15 06:19 UTC, chioreandan commented on script.js
> +    dishContainerDiv.appendChild(createInfoElement(element));
add space after method actions

2021-04-15 11:53 UTC, cristichirtos commented
@chioreandan I added all the spaces after constants and after the actions of functions in script.js. Let me know what you think!

2021-04-19 07:39 UTC, chioreandan approved these changes
Nice job @cristichirtos

2021-04-19 07:42 UTC, cristichirtos commented
Thank you!

2021-04-19 07:42 UTC, merged